---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alchemyst-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
  template:
    spec:
      containers:
        - name: alchemyst
          image: alchemyst-backend:SET_BY_CI
          env:
          - name: DATA_STORE_NAMESPACE
            value: "Alchemyst"
          - name: DATA_STORE_PROJECT
            value: $GCP_PROJECT_ID
          - name: GOOGLE_CLOUD_PROJECT
            value: $GCP_PROJECT_ID
          ports:
          - name: http
            containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          workingDir: /app
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
      serviceAccountName: alchemyst
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: alchemyst
              topologyKey: "kubernetes.io/hostname"
            weight: 100
