apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alchemyst

commonLabels:
  app: alchemyst-backend

resources:
- backend.yaml
- pdb.yaml
- service.yaml
- service-monitor.yaml