---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alchemyst

resources:
- backend.yaml
- pdb.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app: alchemyst-backend
