---
kind: pipeline
name: alchemyst

steps:
- name: publish-base-image 
  image: plugins/docker
  settings:
    username: mosstech
    password:
      from_secret: DOCKER_REGISTRY_PASS
    repo: mosstech/alchemyst-base
    tags: cached
    dockerfile: Dockerfile.base
  when:
    event:
      include:
      - tag

- name: publish-test-image  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo:
      from_secret: MW_GCR_IMAGE_TEST
    tags: ${DRONE_COMMIT_SHA}
    dockerfile: Dockerfile.test
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master

- name: publish-runtime  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo:
      from_secret: MW_GCR_IMAGE
    tags: ${DRONE_COMMIT_SHA}
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master

- name: deploy
  image: mosstech/drone-gke-deployer:latest
  environment:
    NAMESPACE: alchemyst
    GCP_PROJECT_ID:
      from_secret: MW_GCP_PROJECT
    K8S_DEPLOYER_CREDS:
      from_secret: MW_K8S_DEPLOYER
    K8S_CLUSTER_NAME:
      from_secret: MW_K8S_CLUSTER_NAME
  commands:
  - ./go deploy
  when:
    event: push
    branch: master
