version: "3.1"

services:

  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    container_name: alchemyst-frontend
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    container_name: alchemyst-backend
    working_dir: /app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
