---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: alchemyst
spec:
  parentRefs:
  - kind: Gateway
    name: shared-gateway
    namespace: ingress
  hostnames:
  - alchemyst.co.uk
  - www.alchemyst.co.uk
  rules:
  - backendRefs:
    - name: alchemyst-frontend
      port: 8080
