---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alchemyst
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # I'm going to burn in hell ...
    nginx.org/server-snippets: |
      location = /js/visits.js {
        proxy_pass https://plausible.alexos.dev/js/plausible.outbound-links.js;
        proxy_buffering on;
        proxy_set_header Host plausible.alexos.dev;
        proxy_ssl_name plausible.alexos.dev;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse off;
      }
      location = /api/event {
        proxy_pass https://plausible.alexos.dev/api/event;
        proxy_buffering on;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header Host plausible.alexos.dev;
        proxy_ssl_name plausible.alexos.dev;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse off;
      }
spec:
  tls:
    - secretName: alchemyst-tls
      hosts:
        - alchemyst.co.uk
        - www.alchemyst.co.uk
  rules:
    - host: alchemyst.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alchemyst
                port:
                  name: http
    - host: www.alchemyst.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alchemyst
                port:
                  name: http
