apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alchemyst

commonLabels:
  app: alchemyst

resources:
- deployment.yaml
- ingress.yaml
- pdb.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml