apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alchemyst

commonLabels:
  app: alchemyst

resources:
- certificate.yaml
- deployment.yaml
- ingress.yaml
- pdb.yaml
- service.yaml
