---
apiVersion: v1
kind: Service
metadata:
  name: alchemyst
spec:
  type: NodePort
  ports:
    - port: 5000
      name: http
---
apiVersion: v1
kind: Service 
metadata:     
  name: alchemyst-istio
spec:
  type: NodePort
  ports:
  - name: istio-proxy
    port: 15020
    protocol: TCP
