---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alchemyst
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alchemyst
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alchemyst-istio
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alchemyst
  endpoints:
  - interval: 30s
    path: /stats/prometheus
    port: istio-proxy
